version: "3.8"
services:
    db:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: gevs_production
            MYSQL_USER: gevs
            MYSQL_PASSWORD: gevs
        volumes:
            - db_data:/var/lib/mysql
        restart: always

    backend:
        build: 
            context: ./backend
        command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
        volumes:
            - ./backend:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DATABASE_USER: gevs
            DATABASE_PASSWORD: gevs
            DATABASE_HOST: db
            DATABASE_PORT: 3306
            ADMIN_EMAIL: election@shangrila.gov.sr
            ADMIN_PASSWORD: shangrila2024$
            RAILS_FORCE_SSL: "false"

    frontend:
        build: 
            context: ./frontend
        command: npm start
        volumes:
            - ./frontend:/app
        ports:
            - "8080:80"
        depends_on:
            - backend
        environment:
            VITE_BACKEND_BASE_URL: http://localhost:3000

volumes:
    db_data: {}